<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create(['name' => 'Sin país', 'continent_id' => 1]);
        Country::create(['name' => 'Afganistán', 'continent_id' => 5]);
        Country::create(['name' => 'Albania', 'continent_id' => 6]);
        Country::create(['name' => 'Alemania', 'continent_id' => 7]);
        Country::create(['name' => 'Andorra', 'continent_id' => 6]);
        Country::create(['name' => 'Angola', 'continent_id' => 2]);
        Country::create(['name' => 'Antigua y Barbuda', 'continent_id' => 3]);
        Country::create(['name' => 'Arabia Saudita', 'continent_id' => 5]);
        Country::create(['name' => 'Argelia', 'continent_id' => 2]);
        Country::create(['name' => 'Argentina', 'continent_id' => 3]);
        Country::create(['name' => 'Armenia', 'continent_id' => 6]);
        Country::create(['name' => 'Australia', 'continent_id' => 8]);
        Country::create(['name' => 'Austria', 'continent_id' => 7]);
        Country::create(['name' => 'Azerbaiyán', 'continent_id' => 6]);
        Country::create(['name' => 'Bahamas', 'continent_id' => 3]);
        Country::create(['name' => 'Bangladés', 'continent_id' => 5]);
        Country::create(['name' => 'Barbados', 'continent_id' => 3]);
        Country::create(['name' => 'Baréin', 'continent_id' => 5]);
        Country::create(['name' => 'Bélgica', 'continent_id' => 7]);
        Country::create(['name' => 'Belice', 'continent_id' => 3]);
        Country::create(['name' => 'Benín', 'continent_id' => 2]);
        Country::create(['name' => 'Bielorrusia', 'continent_id' => 6]);
        Country::create(['name' => 'Birmania', 'continent_id' => 5]);
        Country::create(['name' => 'Bolivia', 'continent_id' => 3]);
        Country::create(['name' => 'Bosnia y Herzegovina', 'continent_id' => 6]);
        Country::create(['name' => 'Botsuana', 'continent_id' => 2]);
        Country::create(['name' => 'Brasil', 'continent_id' => 3]);
        Country::create(['name' => 'Brunéi', 'continent_id' => 5]);
        Country::create(['name' => 'Bulgaria', 'continent_id' => 7]);
        Country::create(['name' => 'Burkina Faso', 'continent_id' => 2]);
        Country::create(['name' => 'Burundi', 'continent_id' => 2]);
        Country::create(['name' => 'Bután', 'continent_id' => 5]);
        Country::create(['name' => 'Cabo Verde', 'continent_id' => 2]);
        Country::create(['name' => 'Camboya', 'continent_id' => 5]);
        Country::create(['name' => 'Camerún', 'continent_id' => 2]);
        Country::create(['name' => 'Canadá', 'continent_id' => 3]);
        Country::create(['name' => 'Catar', 'continent_id' => 5]);
        Country::create(['name' => 'Chad', 'continent_id' => 2]);
        Country::create(['name' => 'Chile', 'continent_id' => 3]);
        Country::create(['name' => 'China', 'continent_id' => 5]);
        Country::create(['name' => 'Chipre', 'continent_id' => 7]);
        Country::create(['name' => 'Ciudad del Vaticano', 'continent_id' => 6]);
        Country::create(['name' => 'Colombia', 'continent_id' => 3]);
        Country::create(['name' => 'Comoras', 'continent_id' => 2]);
        Country::create(['name' => 'Corea del Norte', 'continent_id' => 5]);
        Country::create(['name' => 'Corea del Sur', 'continent_id' => 5]);
        Country::create(['name' => 'Costa de Marfil', 'continent_id' => 2]);
        Country::create(['name' => 'Costa Rica', 'continent_id' => 3]);
        Country::create(['name' => 'Croacia', 'continent_id' => 7]);
        Country::create(['name' => 'Cuba', 'continent_id' => 3]);
        Country::create(['name' => 'Dinamarca', 'continent_id' => 7]);
        Country::create(['name' => 'Dominica', 'continent_id' => 3]);
        Country::create(['name' => 'Ecuador', 'continent_id' => 3]);
        Country::create(['name' => 'Egipto', 'continent_id' => 2]);
        Country::create(['name' => 'El Salvador', 'continent_id' => 3]);
        Country::create(['name' => 'Emiratos Árabes Unidos', 'continent_id' => 5]);
        Country::create(['name' => 'Eritrea', 'continent_id' => 2]);
        Country::create(['name' => 'Eslovaquia', 'continent_id' => 7]);
        Country::create(['name' => 'Eslovenia', 'continent_id' => 7]);
        Country::create(['name' => 'España', 'continent_id' => 7]);
        Country::create(['name' => 'Estados Unidos', 'continent_id' => 3]);
        Country::create(['name' => 'Estonia', 'continent_id' => 7]);
        Country::create(['name' => 'Etiopía', 'continent_id' => 2]);
        Country::create(['name' => 'Filipinas', 'continent_id' => 5]);
        Country::create(['name' => 'Finlandia', 'continent_id' => 7]);
        Country::create(['name' => 'Fiyi', 'continent_id' => 8]);
        Country::create(['name' => 'Francia', 'continent_id' => 7]);
        Country::create(['name' => 'Gabón', 'continent_id' => 2]);
        Country::create(['name' => 'Gambia', 'continent_id' => 2]);
        Country::create(['name' => 'Georgia', 'continent_id' => 6]);
        Country::create(['name' => 'Ghana', 'continent_id' => 2]);
        Country::create(['name' => 'Granada', 'continent_id' => 3]);
        Country::create(['name' => 'Grecia', 'continent_id' => 7]);
        Country::create(['name' => 'Guatemala', 'continent_id' => 3]);
        Country::create(['name' => 'Guyana', 'continent_id' => 3]);
        Country::create(['name' => 'Guinea', 'continent_id' => 2]);
        Country::create(['name' => 'Guinea ecuatorial', 'continent_id' => 2]);
        Country::create(['name' => 'Guinea-Bisáu', 'continent_id' => 2]);
        Country::create(['name' => 'Haití', 'continent_id' => 3]);
        Country::create(['name' => 'Honduras', 'continent_id' => 3]);
        Country::create(['name' => 'Hungría', 'continent_id' => 7]);
        Country::create(['name' => 'India', 'continent_id' => 5]);
        Country::create(['name' => 'Indonesia', 'continent_id' => 5]);
        Country::create(['name' => 'Irak', 'continent_id' => 5]);
        Country::create(['name' => 'Irán', 'continent_id' => 5]);
        Country::create(['name' => 'Irlanda', 'continent_id' => 7]);
        Country::create(['name' => 'Islandia', 'continent_id' => 6]);
        Country::create(['name' => 'Islas Marshall', 'continent_id' => 8]);
        Country::create(['name' => 'Islas Salomón', 'continent_id' => 8]);
        Country::create(['name' => 'Israel', 'continent_id' => 5]);
        Country::create(['name' => 'Italia', 'continent_id' => 7]);
        Country::create(['name' => 'Jamaica', 'continent_id' => 3]);
        Country::create(['name' => 'Japón', 'continent_id' => 5]);
        Country::create(['name' => 'Jordania', 'continent_id' => 5]);
        Country::create(['name' => 'Kazajistán', 'continent_id' => 5]);
        Country::create(['name' => 'Kenia', 'continent_id' => 2]);
        Country::create(['name' => 'Kirguistán', 'continent_id' => 5]);
        Country::create(['name' => 'Kiribati', 'continent_id' => 8]);
        Country::create(['name' => 'Kuwait', 'continent_id' => 5]);
        Country::create(['name' => 'Laos', 'continent_id' => 5]);
        Country::create(['name' => 'Lesoto', 'continent_id' => 2]);
        Country::create(['name' => 'Letonia', 'continent_id' => 7]);
        Country::create(['name' => 'Líbano', 'continent_id' => 5]);
        Country::create(['name' => 'Liberia', 'continent_id' => 2]);
        Country::create(['name' => 'Libia', 'continent_id' => 2]);
        Country::create(['name' => 'Liechtenstein', 'continent_id' => 6]);
        Country::create(['name' => 'Lituania', 'continent_id' => 7]);
        Country::create(['name' => 'Luxemburgo', 'continent_id' => 7]);
        Country::create(['name' => 'Madagascar', 'continent_id' => 2]);
        Country::create(['name' => 'Malasia', 'continent_id' => 5]);
        Country::create(['name' => 'Malaui', 'continent_id' => 2]);
        Country::create(['name' => 'Maldivas', 'continent_id' => 5]);
        Country::create(['name' => 'Malí', 'continent_id' => 2]);
        Country::create(['name' => 'Malta', 'continent_id' => 7]);
        Country::create(['name' => 'Marruecos', 'continent_id' => 2]);
        Country::create(['name' => 'Mauricio', 'continent_id' => 2]);
        Country::create(['name' => 'Mauritania', 'continent_id' => 2]);
        Country::create(['name' => 'México', 'continent_id' => 3]);
        Country::create(['name' => 'Micronesia', 'continent_id' => 8]);
        Country::create(['name' => 'Moldavia', 'continent_id' => 6]);
        Country::create(['name' => 'Mónaco', 'continent_id' => 6]);
        Country::create(['name' => 'Mongolia', 'continent_id' => 5]);
        Country::create(['name' => 'Montenegro', 'continent_id' => 6]);
        Country::create(['name' => 'Mozambique', 'continent_id' => 2]);
        Country::create(['name' => 'Namibia', 'continent_id' => 2]);
        Country::create(['name' => 'Nauru', 'continent_id' => 8]);
        Country::create(['name' => 'Nepal', 'continent_id' => 5]);
        Country::create(['name' => 'Nicaragua', 'continent_id' => 3]);
        Country::create(['name' => 'Níger', 'continent_id' => 2]);
        Country::create(['name' => 'Nigeria', 'continent_id' => 2]);
        Country::create(['name' => 'Noruega', 'continent_id' => 6]);
        Country::create(['name' => 'Nueva Zelanda', 'continent_id' => 8]);
        Country::create(['name' => 'Omán', 'continent_id' => 5]);
        Country::create(['name' => 'Países Bajos', 'continent_id' => 7]);
        Country::create(['name' => 'Pakistán', 'continent_id' => 5]);
        Country::create(['name' => 'Palaos', 'continent_id' => 8]);
        Country::create(['name' => 'Panamá', 'continent_id' => 3]);
        Country::create(['name' => 'Papúa Nueva Guinea', 'continent_id' => 8]);
        Country::create(['name' => 'Paraguay', 'continent_id' => 3]);
        Country::create(['name' => 'Perú', 'continent_id' => 3]);
        Country::create(['name' => 'Polonia', 'continent_id' => 7]);
        Country::create(['name' => 'Portugal', 'continent_id' => 7]);
        Country::create(['name' => 'Reino Unido', 'continent_id' => 6]);
        Country::create(['name' => 'República Centroafricana', 'continent_id' => 2]);
        Country::create(['name' => 'República Checa', 'continent_id' => 7]);
        Country::create(['name' => 'República de Macedonia', 'continent_id' => 6]);
        Country::create(['name' => 'República del Congo', 'continent_id' => 2]);
        Country::create(['name' => 'República Democrática del Congo', 'continent_id' => 2]);
        Country::create(['name' => 'República Dominicana', 'continent_id' => 3]);
        Country::create(['name' => 'República Sudafricana', 'continent_id' => 2]);
        Country::create(['name' => 'Ruanda', 'continent_id' => 2]);
        Country::create(['name' => 'Rumanía', 'continent_id' => 7]);
        Country::create(['name' => 'Rusia', 'continent_id' => 6]);
        Country::create(['name' => 'Samoa', 'continent_id' => 8]);
        Country::create(['name' => 'San Cristóbal y Nieves', 'continent_id' => 3]);
        Country::create(['name' => 'San Marino', 'continent_id' => 6]);
        Country::create(['name' => 'San Vicente y las Granadinas', 'continent_id' => 3]);
        Country::create(['name' => 'Santa Lucía', 'continent_id' => 3]);
        Country::create(['name' => 'Santo Tomé y Príncipe', 'continent_id' => 2]);
        Country::create(['name' => 'Senegal', 'continent_id' => 2]);
        Country::create(['name' => 'Serbia', 'continent_id' => 6]);
        Country::create(['name' => 'Seychelles', 'continent_id' => 2]);
        Country::create(['name' => 'Sierra Leona', 'continent_id' => 2]);
        Country::create(['name' => 'Singapur', 'continent_id' => 5]);
        Country::create(['name' => 'Siria', 'continent_id' => 5]);
        Country::create(['name' => 'Somalia', 'continent_id' => 2]);
        Country::create(['name' => 'Sri Lanka', 'continent_id' => 5]);
        Country::create(['name' => 'Suazilandia', 'continent_id' => 2]);
        Country::create(['name' => 'Sudán', 'continent_id' => 2]);
        Country::create(['name' => 'Sudán del Sur', 'continent_id' => 2]);
        Country::create(['name' => 'Suecia', 'continent_id' => 7]);
        Country::create(['name' => 'Suiza', 'continent_id' => 6]);
        Country::create(['name' => 'Surinam', 'continent_id' => 3]);
        Country::create(['name' => 'Tailandia', 'continent_id' => 5]);
        Country::create(['name' => 'Tanzania', 'continent_id' => 2]);
        Country::create(['name' => 'Tayikistán', 'continent_id' => 5]);
        Country::create(['name' => 'Timor Oriental', 'continent_id' => 5]);
        Country::create(['name' => 'Togo', 'continent_id' => 2]);
        Country::create(['name' => 'Tonga', 'continent_id' => 8]);
        Country::create(['name' => 'Trinidad y Tobago', 'continent_id' => 3]);
        Country::create(['name' => 'Túnez', 'continent_id' => 2]);
        Country::create(['name' => 'Turkmenistán', 'continent_id' => 5]);
        Country::create(['name' => 'Turquía', 'continent_id' => 5]);
        Country::create(['name' => 'Tuvalu', 'continent_id' => 8]);
        Country::create(['name' => 'Ucrania', 'continent_id' => 6]);
        Country::create(['name' => 'Uganda', 'continent_id' => 2]);
        Country::create(['name' => 'Uruguay', 'continent_id' => 3]);
        Country::create(['name' => 'Uzbekistán', 'continent_id' => 5]);
        Country::create(['name' => 'Vanuatu', 'continent_id' => 8]);
        Country::create(['name' => 'Venezuela', 'continent_id' => 3]);
        Country::create(['name' => 'Vietnam', 'continent_id' => 5]);
        Country::create(['name' => 'Yemen', 'continent_id' => 5]);
        Country::create(['name' => 'Yibuti', 'continent_id' => 2]);
        Country::create(['name' => 'Zambia', 'continent_id' => 2]);
        Country::create(['name' => 'Zimbabue', 'continent_id' => 2]);
    }
}
