<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CountryIsoCodes extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('countries', function (Blueprint $table) {
            $table->string('iso')->nullable();
        });

        $countries = [
            2 => "AF",
            3 => "AL",
            4 => "DE",
            5 => "AD",
            6 => "AO",
            7 => "AG",
            8 => "SA",
            9 => "DZ",
            10 => "AR",
            11 => "AM",
            12 => "AU",
            13 => "AT",
            14 => "AZ",
            15 => "BS",
            16 => "BD",
            17 => "BB",
            18 => "BH",
            19 => "BE",
            20 => "BZ",
            21 => "BJ",
            22 => "BY",
            23 => "MM",
            24 => "BO",
            25 => "BA",
            26 => "BW",
            27 => "BR",
            28 => "BN",
            29 => "BG",
            30 => "BF",
            31 => "BI",
            32 => "BT",
            33 => "CV",
            34 => "KH",
            35 => "CM",
            36 => "CA",
            37 => "QA",
            38 => "TD",
            39 => "CL",
            40 => "CN",
            41 => "CY",
            42 => "VA",
            43 => "CO",
            44 => "KM",
            45 => "KP",
            46 => "KR",
            47 => "CI",
            48 => "CR",
            49 => "HR",
            50 => "CU",
            51 => "DK",
            52 => "DM",
            53 => "EC",
            54 => "EG",
            55 => "SV",
            56 => "AE",
            57 => "ER",
            58 => "SK",
            59 => "SI",
            60 => "ES",
            61 => "US",
            62 => "EE",
            63 => "ET",
            64 => "PH",
            65 => "FI",
            66 => "FJ",
            67 => "FR",
            68 => "GA",
            69 => "GM",
            70 => "GE",
            71 => "GH",
            72 => "GD",
            73 => "GR",
            74 => "GT",
            75 => "GY",
            76 => "GN",
            77 => "GQ",
            78 => "GW",
            79 => "HT",
            80 => "HN",
            81 => "HU",
            82 => "IN",
            83 => "ID",
            84 => "IQ",
            85 => "IR",
            86 => "IE",
            87 => "IS",
            88 => "MH",
            89 => "SB",
            90 => "IL",
            91 => "IT",
            92 => "JM",
            93 => "JP",
            94 => "JO",
            95 => "KZ",
            96 => "KE",
            97 => "KG",
            98 => "KI",
            99 => "KW",
            100 => "LA",
            101 => "LS",
            102 => "LV",
            103 => "LB",
            104 => "LR",
            105 => "LY",
            106 => "LI",
            107 => "LT",
            108 => "LU",
            109 => "MG",
            110 => "MY",
            111 => "MW",
            112 => "MV",
            113 => "ML",
            114 => "MT",
            115 => "MA",
            116 => "MU",
            117 => "MR",
            118 => "MX",
            119 => "FM",
            120 => "MD",
            121 => "MC",
            122 => "MN",
            123 => "ME",
            124 => "MZ",
            125 => "NA",
            126 => "NR",
            127 => "NP",
            128 => "NI",
            129 => "NE",
            130 => "NG",
            131 => "NO",
            132 => "NZ",
            133 => "OM",
            134 => "NL",
            135 => "PK",
            136 => "PW",
            137 => "PA",
            138 => "PG",
            139 => "PY",
            140 => "PE",
            141 => "PL",
            142 => "PT",
            143 => "GB",
            144 => "CF",
            145 => "CZ",
            146 => "MK",
            147 => "CG",
            148 => "CD",
            149 => "DO",
            150 => "ZA",
            151 => "RW",
            152 => "RO",
            153 => "RU",
            154 => "WS",
            155 => "KN",
            156 => "SM",
            157 => "VC",
            158 => "LC",
            159 => "ST",
            160 => "SN",
            161 => "RS",
            162 => "SC",
            163 => "SL",
            164 => "SG",
            165 => "SY",
            166 => "SO",
            167 => "LK",
            168 => "SZ",
            169 => "SD",
            170 => "SS",
            171 => "SE",
            172 => "CH",
            173 => "SR",
            174 => "TH",
            175 => "TZ",
            176 => "TJ",
            177 => "TL",
            178 => "TG",
            179 => "TO",
            180 => "TT",
            181 => "TN",
            182 => "TM",
            183 => "TR",
            184 => "TV",
            185 => "UA",
            186 => "UG",
            187 => "UY",
            188 => "UZ",
            189 => "VU",
            190 => "VE",
            191 => "VN",
            192 => "YE",
            193 => "DJ",
            194 => "ZM",
            195 => "ZW"
        ];
        foreach ($countries as $country => $iso) {
            DB::table('countries')->where('id', $country)->update(['iso' => $iso]);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('countries', function (Blueprint $table) {
            $table->dropColumn(['iso']);
        });
    }
}
